name: QA Tests
'on':
  workflow_dispatch: null
  workflow_call: null
env:
  GTEST_COLOR: 1
  GTEST_THROW_ON_FAILURE: 0
  SKIP_FORMAT_BUCK_CHECKS: 1
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:18.04
      volumes:
      - /var/tmp:/var/tmp
      - /tmp:/tmp
    strategy:
      matrix:
        include:
        - name: Unit tests
          short_test: TMPD="$(mktemp -d /tmp/speedb.XXXX)" make -j$(nproc) check
          long_test: TMPD="$(mktemp -d /tmp/speedb.XXXX)" make -j$(nproc) check
        - name: black-box
          short_test: CRASH_TEST_EXT_ARGS="--duration=3600" make -j$(nproc) blackbox_asan_crash_test
          long_test: CRASH_TEST_EXT_ARGS="--duration=10000" make -j$(nproc) blackbox_asan_crash_test
        - name: white-box
          short_test: CRASH_TEST_EXT_ARGS="--duration=3600" make -j$(nproc) whitebox_asan_crash_test
          long_test: CRASH_TEST_EXT_ARGS="--duration=10000" make -j$(nproc) whitebox_asan_crash_test
    steps:
    - name: Network hotfix
      run: echo "nameserver 8.8.8.8" > /etc/resolv.conf
    - name: Pre
      run: 'apt update -y

        apt install -y build-essential clang-format parallel libgflags-dev liblz4-dev
        libsnappy-dev libzstd-dev python3 python3-pip curl

        '
    - name: Checkout
      uses: actions/checkout@v3
    - name: ${{ matrix.name }}
      run: "case \"$GITHUB_REF_NAME\" in\n  release/*)\n    echo \"Running long test\
        \ for release, $(nproc) jobs\"\n    make clean && ${{ matrix.long_test }}\n\
        \    ;;\n  *)\n    echo \"Running short test, $(nproc) jobs\"\n    make clean\
        \ && ${{ matrix.short_test }}\n    ;;\nesac\n"
    - name: Save the DB if the test failed
      if: ${{ failure() }}
      id: savedb
      run: "ls -l /tmp/rocksdb_crashtest_* \ntar -zcvf /tmp/db4debug.tar.gz /tmp/rocksdb_crashtest_*\
        \ \nls -l /tmp/db4debug.tar.gz\n"
    - name: Upload the DB
      uses: actions/upload-artifact@v3
      if: ${{ always() && steps.savedb.outcome != 'skipped' && steps.savedb.outcome
        != 'failure' }}
      with:
        name: testdb
        retention-days: 3
        path: /tmp/db4debug.tar.gz
